version: '3.9'

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build: ./rails
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    ports:
      - "5000:3000"
    volumes:
      - ./rails:/rails
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      RAILS_ENV: development
    tty: true
    stdin_open: true

  api:
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password

volumes:
  mysql_data:
