vegetables = [
  { name: "じゃがいも", season: 0, region: "北海道, 鹿児島県, 長崎県, 茨城県, 千葉県", difficulty: 1, description: "日本一の収穫量。春夏植えとも栽培可能。" },
  { name: "キャベツ", season: 1, region: "北海道, 群馬県, 千葉県, 愛知県, 熊本県", difficulty: 2, description: "春秋・冬作あり。虫害に注意。" },
  { name: "だいこん", season: 2, region: "千葉県, 北海道, 茨城県, 愛知県, 熊本県", difficulty: 1, description: "日本全国で栽培。種類豊富で用途多様。" },
  { name: "ほうれんそう", season: 3, region: "茨城県, 千葉県, 群馬県, 北海道, 長野県", difficulty: 1, description: "冬場の栽培が盛ん。葉が濃緑色。" },
  { name: "トマト", season: 1, region: "熊本県, 北海道, 茨城県, 福岡県, 群馬県", difficulty: 2, description: "温暖地・施設栽培向き。夏の代表果菜。" },
  { name: "なす", season: 1, region: "高知県, 熊本県, 宮崎県, 茨城県, 愛知県", difficulty: 2, description: "夏野菜の代表。多湿に弱いので管理注意。" },
  { name: "きゅうり", season: 1, region: "茨城県, 熊本県, 群馬県, 長野県, 福岡県", difficulty: 1, description: "生食向き。夏季の栽培が中心。" },
  { name: "ピーマン", season: 1, region: "千葉県, 茨城県, 熊本県, 愛知県, 宮崎県", difficulty: 2, description: "緑・赤色品種あり。夏に収穫。" },
  { name: "さつまいも", season: 1, region: "鹿児島県, 宮崎県, 熊本県, 茨城県, 千葉県", difficulty: 2, description: "暖地向き。栄養価高い根菜。" },
  { name: "にんじん", season: 2, region: "北海道, 千葉県, 茨城県, 北海道, 長野県", difficulty: 1, description: "多用途の根菜。冷涼地でよく育つ。" },
  { name: "たまねぎ", season: 3, region: "北海道, 兵庫県, 青森県, 長野県, 茨城県", difficulty: 2, description: "春まき秋収穫が主流。保存性良し。" },
  { name: "レタス", season: 0, region: "茨城県, 北海道, 長野県, 群馬県, 千葉県", difficulty: 1, description: "サラダ用。冷涼地での栽培が多い。" },
  { name: "ブロッコリー", season: 0, region: "茨城県, 北海道, 長野県, 愛知県, 群馬県", difficulty: 3, description: "花蕾と茎を利用。指定野菜リストに準ずる。" },
  { name: "カリフラワー", season: 0, region: "千葉県, 愛知県, 北海道, 長野県, 群馬県", difficulty: 3, description: "白い花蕾を食用とする西洋野菜。" },
  { name: "春キャベツ", season: 0, region: "群馬県, 千葉県, 愛知県, 北海道, 長野県", difficulty: 2, description: "甘味強く生食向き。春どり品種。" },
  { name: "芽キャベツ", season: 0, region: "長野県, 北海道, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "小さな球を茎に多数つける西洋野菜。" },
  { name: "ビーツ", season: 0, region: "北海道, 長野県, 群馬県, 茨城県, 愛知県", difficulty: 3, description: "根菜。鮮やかな色が特徴。冷涼地向き。" },
  { name: "パプリカ", season: 0, region: "千葉県, 北海道, 茨城県, 宮崎県, 愛知県", difficulty: 3, description: "トマトと同じナス科。西洋野菜。色が多彩。" },
  { name: "ロメインレタス", season: 0, region: "千葉県, 長野県, 北海道, 茨城県, 群馬県", difficulty: 2, description: "サラダ用。葉が厚く食感しっかり。" },
  { name: "オクラ", season: 1, region: "沖縄県, 鹿児島県, 宮崎県, 千葉県, 茨城県", difficulty: 2, description: "高温・多湿に強い夏野菜。" },
  { name: "モロヘイヤ", season: 1, region: "沖縄県, 鹿児島県, 宮崎県, 高知県, 愛媛県", difficulty: 2, description: "暑さに強く栄養価高い葉茎菜。" },
  { name: "ビンチョウ", season: 0, region: "栃木県, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 2, description: "水菜に似る。冬春に収穫される葉物。" },
  { name: "コールラビ", season: 0, region: "北海道, 長野県, 群馬県, 千葉県, 茨城県", difficulty: 3, description: "芥子のような球茎が特徴の西洋野菜。" },
  { name: "ラディッシュ", season: 2, region: "長野県, 北海道, 群馬県, 千葉県, 茨城県", difficulty: 1, description: "小型根菜。栽培期間短く初心者向き。" },
  { name: "ミニトマト", season: 1, region: "北海道, 長野県, 茨城県, 熊本県, 愛知県", difficulty: 3, description: "ミニ果実。雨よけ栽培が望ましい。" },
  { name: "チャード", season: 0, region: "北海道, 群馬県, 長野県, 千葉県, 茨城県", difficulty: 2, description: "スイスチャード。色彩豊かな西洋葉菜。" },
  { name: "チャイニーズキャベツ", season: 1, region: "茨城県, 長野県, 千葉県, 愛知県, 北海道", difficulty: 2, description: "白菜に似るが早生でトウ立ちしやすい。" },
  { name: "ケール", season: 1, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 2, description: "青汁原料。栄養価が非常に高い葉菜。" },
  { name: "カリフロレス", season: 0, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "小型カリフラワー。食べやすいサイズ。" },
  { name: "エシャロット", season: 0, region: "北海道, 長野県, 茨城県, 香川県, 鹿児島県", difficulty: 3, description: "西洋ネギ。香り高い球根野菜。" },
  { name: "セルリアック", season: 0, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "セロリアック。根を食べる西洋野菜。" },
  { name: "フェンネル", season: 0, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "セリ科。茎と葉が香味に使われる。" },
  { name: "スイスチャード", season: 0, region: "北海道, 群馬県, 長野県, 千葉県, 茨城県", difficulty: 2, description: "ビーツの葉。色彩豊かな葉物。" },
  { name: "ロケット（ルッコラ）", season: 2, region: "茨城県, 千葉県, 北海道, 群馬県, 長野県", difficulty: 1, description: "辛味と香りのある葉菜。サラダ向き。" },
  { name: "オニオンリーク", season: 0, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "西洋ネギ。スープの香味に。" },
  { name: "ヤーコン", season: 0, region: "北海道, 長野県, 群馬県, 茨城県, 栃木県", difficulty: 2, description: "根菜。シャキシャキした食感。" },
  { name: "レンバイタ", season: 1, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 2, description: "西洋二十日大根。短期間で収穫可。" },
  { name: "カラシナ", season: 2, region: "千葉県, 茨城県, 埼玉県, 東京, 神奈川県", difficulty: 1, description: "辛味のある葉菜。お浸しや漬物に。" },
  { name: "マスタードグリーン", season: 2, region: "千葉県, 茨城県, 北海道, 群馬県, 長野県", difficulty: 2, description: "辛目の葉物。炒め物に向く。" },
  { name: "ターサイ", season: 1, region: "千葉県, 茨城県, 埼玉県, 北海道, 長野県", difficulty: 2, description: "中華野菜。耐寒性あり。炒め物向き。" },
  { name: "コールスプラウト", season: 0, region: "長野県, 北海道, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "芽キャベツのような芽を食す。" },
  { name: "ホワイトアスパラガス", season: 0, region: "北海道, 長野県, 群馬県, 茨城県, 北海道", difficulty: 3, description: "アスパラガスの白色品種。" },
  { name: "ブラムベリー", season: 0, region: "北海道, 長野県, 茨城県, 群馬県, 千葉県", difficulty: 3, description: "西洋ハーブ。彩りに良い葉茎菜。" },
  { name: "パースニップ", season: 1, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "西洋パセリ根菜。甘味ある根部。" },
  { name: "チャイブ", season: 2, region: "北海道, 長野県, 群馬県, 茨城県, 愛知県", difficulty: 1, description: "西洋ネギ。香味に使われる葉茎菜。" },
  { name: "水菜（京水菜）", season: 2, region: "京都府, 埼玉県, 千葉県, 茨城県, 北海道", difficulty: 1, description: "京産の品種。サラダや鍋に。" },
  { name: "セルフィーユ", season: 2, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "香味草。炒め物やスープに。" },
  { name: "エンドウ豆らい", season: 2, region: "北海道, 長野県, 愛知県, 栃木県, 青森県", difficulty: 2, description: "らい豆。茹でで食用。" },
  { name: "アーティチョーク", season: 0, region: "長野県, 北海道, 群馬県, 茨城県, 千葉県", difficulty: 4, description: "花蕾を食べる高難度西洋野菜。" },
  { name: "タンポポ菜", season: 1, region: "茨城県, 千葉県, 埼玉県, 東京, 神奈川県", difficulty: 2, description: "野生鮮野菜。苦味ある葉菜。" },
  { name: "ウォータークレス", season: 1, region: "北海道, 長野県, 群馬県, 茨城県, 千葉県", difficulty: 3, description: "水辺に育つ葉茎菜。独特の辛味。" },
  { name: "島らっきょう", season: 1, region: "沖縄県", difficulty: 1, description: "沖縄の香味野菜。炒め物や漬物に適する。" },
  { name: "空芯菜", season: 1, region: "沖縄県, 鹿児島県, 熊本県, 高知県, 愛知県", difficulty: 0, description: "熱帯原産の夏野菜。水耕にも適する。" },
  { name: "赤からし菜", season: 2, region: "福岡県, 熊本県, 長崎県, 佐賀県, 愛知県", difficulty: 1, description: "葉に紫がかる。漬物や炒め物向き。" },
  { name: "つるむらさき", season: 1, region: "沖縄県, 鹿児島県, 宮崎県, 高知県, 大分県", difficulty: 0, description: "夏の栄養豊富なつる性野菜。" },
  { name: "のらぼう菜", season: 0, region: "東京都, 神奈川県, 埼玉県, 山梨県, 群馬県", difficulty: 0, description: "江戸東京野菜。春先の収穫が特徴。" },
  { name: "あしたば", season: 3, region: "東京都, 伊豆諸島, 千葉県, 静岡県", difficulty: 1, description: "多年草。新芽を食す栄養豊富な野草。" },
  { name: "行者にんにく", season: 3, region: "北海道, 青森県, 岩手県, 秋田県, 山形県", difficulty: 2, description: "山菜。にんにくのような香り。" },
  { name: "うど", season: 0, region: "東京都, 秋田県, 山形県, 群馬県, 新潟県", difficulty: 1, description: "日陰を好む多年草。山菜として人気。" },
  { name: "金時にんじん", season: 3, region: "京都府, 徳島県, 香川県, 大阪府, 三重県", difficulty: 1, description: "赤みの強い品種。京野菜の一つ。" },
  { name: "丸なす", season: 1, region: "京都府, 熊本県, 岡山県, 徳島県, 滋賀県", difficulty: 1, description: "加熱料理に適する丸型のなす品種。" },
  { name: "白なす", season: 1, region: "群馬県, 栃木県, 京都府, 香川県, 高知県", difficulty: 1, description: "皮が白い品種。焼きなすに最適。" },
  { name: "三太郎大根", season: 2, region: "千葉県, 茨城県, 愛知県, 岐阜県, 長野県", difficulty: 0, description: "短くて丸い大根。初心者向け。" },
  { name: "紅芯大根", season: 2, region: "北海道, 長野県, 茨城県, 群馬県, 千葉県", difficulty: 1, description: "中が赤い彩り大根。サラダ向き。" },
  { name: "青首大根", season: 2, region: "千葉県, 茨城県, 北海道, 熊本県, 愛知県", difficulty: 1, description: "最も一般的な大根種。使いやすい。" },
  { name: "葉だいこん", season: 3, region: "長野県, 群馬県, 千葉県, 埼玉県, 宮城県", difficulty: 0, description: "葉を利用する品種。成長が早い。" },
  { name: "紅くるり大根", season: 2, region: "北海道, 長野県, 群馬県, 千葉県, 福島県", difficulty: 1, description: "表面も内部も赤い。食卓に映える。" },
  { name: "のざわな", season: 3, region: "長野県, 新潟県, 山形県, 群馬県, 福島県", difficulty: 1, description: "漬物に用いられる信州の伝統野菜。" },
  { name: "関西しろな", season: 3, region: "大阪府, 兵庫県, 奈良県, 和歌山県, 京都府", difficulty: 1, description: "関西で人気の冬野菜。汁物や鍋に。" },
  { name: "ちぢみほうれん草", season: 3, region: "北海道, 青森県, 埼玉県, 茨城県, 群馬県", difficulty: 1, description: "寒さで甘くなる冬ほうれん草。" },
  { name: "赤軸ほうれん草", season: 3, region: "千葉県, 茨城県, 群馬県, 北海道, 長野県", difficulty: 1, description: "赤い茎が特徴。彩りと栄養が豊富。" },
]

vegetables.each do |vegetable|
  Vegetable.create!(vegetable)
end
