weeds = [
  {
    name: "スズメノカタビラ",
    scientific_name: "Poa annua",
    description: "寒さに強く、冬から早春にかけて発生する一年草。水分の多い場所を好む。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago asiatica",
    description: "踏まれても強く育つ。地面に広がるように成長し、痩せた土地でもよく育つ。",
    image_url: "",
  },
  {
    name: "カラスノエンドウ",
    scientific_name: "Vicia sativa",
    description: "春に紫の花を咲かせるマメ科の植物。窒素固定能力を持つ。",
    image_url: "",
  },
  {
    name: "ハコベ",
    scientific_name: "Stellaria media",
    description: "湿った土地でよく育つ小型の草。春の七草の一つとしても知られる。",
    image_url: "",
  },
  {
    name: "タンポポ",
    scientific_name: "Taraxacum officinale",
    description: "繁殖力が強く、綿毛で種子を遠くに飛ばす多年草。道端や空き地に多い。",
    image_url: "",
  },
  {
    name: "ナズナ",
    scientific_name: "Capsella bursa-pastoris",
    description: "春の七草の一つ。やせ地や道端でよく見られる。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "夏に白い花を咲かせる帰化植物。やせた土地にも生育する。",
    image_url: "",
  },
  {
    name: "ドクダミ",
    scientific_name: "Houttuynia cordata",
    description: "独特のにおいがあり、湿った半日陰の土地を好む多年草。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Chenopodium album",
    description: "乾燥した場所で育つことが多く、アルカリ性土壌に強い。",
    image_url: "",
  },
  {
    name: "カタバミ",
    scientific_name: "Oxalis corniculata",
    description: "酸性土壌を好み、日陰にも強い多年草。黄色い小花を咲かせる。",
    image_url: "",
  },
  {
    name: "ツユクサ",
    scientific_name: "Commelina communis",
    description: "朝に青い花を咲かせる一年草。水分の多い土壌を好む。",
    image_url: "",
  },
  {
    name: "ヒガンバナ",
    scientific_name: "Lycoris radiata",
    description: "水田のあぜ道に多く見られる多年草。有毒性がある。",
    image_url: "",
  },
  {
    name: "スベリヒユ",
    scientific_name: "Portulaca oleracea",
    description: "乾燥に強く、繁殖力が旺盛。食用や薬用にもなる。",
    image_url: "",
  },
  {
    name: "メヒシバ",
    scientific_name: "Digitaria ciliaris",
    description: "踏まれても強く育つ。夏に強い一年草。",
    image_url: "",
  },
  {
    name: "エノコログサ",
    scientific_name: "Setaria viridis",
    description: "ねこじゃらしの名で親しまれる。肥沃な土地を好む。",
    image_url: "",
  },
  {
    name: "イヌビエ",
    scientific_name: "Echinochloa crus-galli",
    description: "水田や湿地に多く見られるイネ科の雑草。",
    image_url: "",
  },
  {
    name: "チガヤ",
    scientific_name: "Imperata cylindrica",
    description: "酸性土壌にも強く、乾燥にも耐える多年草。",
    image_url: "",
  },
  {
    name: "ギシギシ",
    scientific_name: "Rumex japonicus",
    description: "水辺や湿地によく見られ、大型の葉を持つ。",
    image_url: "",
  },
  {
    name: "シロツメクサ",
    scientific_name: "Trifolium repens",
    description: "クローバーとして親しまれ、窒素固定能力を持つ。",
    image_url: "",
  },
  {
    name: "アメリカセンダングサ",
    scientific_name: "Bidens frondosa",
    description: "繁殖力が高く、ひっつき虫として知られる種子を持つ。",
    image_url: "",
  },
  {
    name: "ムラサキカタバミ",
    scientific_name: "Oxalis corymbosa",
    description: "観賞用として持ち込まれたが、繁殖力が強く雑草化。酸性土壌にも強い。",
    image_url: "",
  },
  {
    name: "オヒシバ",
    scientific_name: "Eleusine indica",
    description: "日当たりの良い場所でよく見かけるイネ科の多年草。踏みつけにも強い。",
    image_url: "",
  },
  {
    name: "セイタカアワダチソウ",
    scientific_name: "Solidago altissima",
    description: "外来種で、高さ2m以上に成長。日当たりのよい土地で旺盛に繁殖。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium spurium",
    description: "フック状の毛で衣服などにくっつく。湿潤な場所を好む。",
    image_url: "",
  },
  {
    name: "キュウリグサ",
    scientific_name: "Trigonotis peduncularis",
    description: "春に青い小花を咲かせる。やや湿った場所でよく見られる。",
    image_url: "",
  },
  {
    name: "ハルジオン",
    scientific_name: "Erigeron philadelphicus",
    description: "春に白や薄紫の花を咲かせる外来雑草。空き地や道端に多い。",
    image_url: "",
  },
  {
    name: "コニシキソウ",
    scientific_name: "Euphorbia maculata",
    description: "地面を這うように広がる一年草。乾燥地にも強く、雑草として厄介。",
    image_url: "",
  },
  {
    name: "アメリカアゼナ",
    scientific_name: "Lindernia dubia",
    description: "湿った場所を好む。小さな花をつける帰化植物。",
    image_url: "",
  },
  {
    name: "ヤブガラシ",
    scientific_name: "Cayratia japonica",
    description: "つる性で樹木に絡みつく。日陰にも強く、除去が難しい。",
    image_url: "",
  },
  {
    name: "ヒメツルソバ",
    scientific_name: "Persicaria capitata",
    description: "地面を覆うように広がる多年草。観賞用から野生化した。",
    image_url: "",
  },
  {
    name: "アレチウリ",
    scientific_name: "Sicyos angulatus",
    description: "繁殖力が極めて強く、河川敷などで問題化している外来種。",
    image_url: "",
  },
  {
    name: "ミチヤナギ",
    scientific_name: "Polygonum arenastrum",
    description: "道端や踏まれる場所でも成長する。乾燥に強い。",
    image_url: "",
  },
  {
    name: "イヌガラシ",
    scientific_name: "Rorippa indica",
    description: "湿地や水田周辺によく見られる。春に黄色い花を咲かせる。",
    image_url: "",
  },
  {
    name: "ホトケノザ",
    scientific_name: "Lamium amplexicaule",
    description: "春の七草の一つ（実際は別種が該当）。湿り気のある場所を好む。",
    image_url: "",
  },
  {
    name: "カラムシ",
    scientific_name: "Boehmeria nivea",
    description: "繊維原料にもなる多年草。半日陰や湿った土地でよく育つ。",
    image_url: "",
  },
  {
    name: "ノゲシ",
    scientific_name: "Sonchus oleraceus",
    description: "柔らかいトゲを持つ葉が特徴。春〜秋に黄色い花を咲かせる。",
    image_url: "",
  },
  {
    name: "カヤツリグサ",
    scientific_name: "Cyperus microiria",
    description: "湿地や水田に多く見られる。多年性のカヤツリグサ科植物。",
    image_url: "",
  },
  {
    name: "ウシハコベ",
    scientific_name: "Stellaria aquatica",
    description: "水辺に自生する多年草。葉がやや厚く、茎は中空。",
    image_url: "",
  },
  {
    name: "オオアレチノギク",
    scientific_name: "Conyza sumatrensis",
    description: "乾燥にも強く、高さ1m以上に成長する外来の帰化雑草。",
    image_url: "",
  },
  {
    name: "マツバウンラン",
    scientific_name: "Nuttallanthus canadensis",
    description: "春に薄紫の花を咲かせる北米原産の帰化植物。",
    image_url: "",
  },
  {
    name: "ハキダメギク",
    scientific_name: "Galinsoga quadriradiata",
    description: "一見地味だが繁殖力は非常に高い。中南米原産の外来種。",
    image_url: "",
  },
  {
    name: "ナズナ",
    scientific_name: "Capsella bursa-pastoris",
    description: "春の七草のひとつ。踏み固められた場所でも育つ。",
    image_url: "",
  },
  {
    name: "コメツブウマゴヤシ",
    scientific_name: "Medicago lupulina",
    description: "マメ科の一年草。乾燥した道端に自生する小型雑草。",
    image_url: "",
  },
  {
    name: "アメリカフウロ",
    scientific_name: "Geranium carolinianum",
    description: "切れ込みのある葉が特徴。春から初夏にかけて見られる。",
    image_url: "",
  },
  {
    name: "トキワハゼ",
    scientific_name: "Mazus pumilus",
    description: "湿地に多く見られる。紫色の小さな花が特徴。",
    image_url: "",
  },
  {
    name: "カタバミ",
    scientific_name: "Oxalis corniculata",
    description: "繁殖力が非常に強く、日陰にも強い多年草。",
    image_url: "",
  },
  {
    name: "スベリヒユ",
    scientific_name: "Portulaca oleracea",
    description: "乾燥に強く、夏場に多く見られる栄養価の高い雑草。",
    image_url: "",
  },
  {
    name: "メヒシバ",
    scientific_name: "Digitaria ciliaris",
    description: "夏に繁茂するイネ科の一年草。日当たりと乾燥に強い。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "白い花を咲かせる外来植物。春から秋まで長く咲く。",
    image_url: "",
  },
  {
    name: "ノビル",
    scientific_name: "Allium macrostemon",
    description: "強いにおいを持つ多年草。土中に小さな球根を作る。",
    image_url: "",
  },
  {
    name: "セリ",
    scientific_name: "Oenanthe javanica",
    description: "水辺に生育する多年草。春の七草のひとつ。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago asiatica",
    description: "踏みつけに強く、道端に多い。薬草としても利用される。",
    image_url: "",
  },
  {
    name: "シロザ",
    scientific_name: "Chenopodium album",
    description: "畑によく出る雑草。種子の数が多く繁殖力が強い。",
    image_url: "",
  },
  {
    name: "タビラコ",
    scientific_name: "Lapsana apogonoides",
    description: "春の七草の「ホトケノザ」とされるキク科の植物。",
    image_url: "",
  },
  {
    name: "ツユクサ",
    scientific_name: "Commelina communis",
    description: "朝に青い花を咲かせる。水分の多い場所を好む。",
    image_url: "",
  },
  {
    name: "チドメグサ",
    scientific_name: "Hydrocotyle sibthorpioides",
    description: "湿地に生え、地面を這うように広がる多年草。",
    image_url: "",
  },
  {
    name: "ハマスゲ",
    scientific_name: "Cyperus rotundus",
    description: "地下茎で増える多年草。根絶が難しい。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium spurium",
    description: "フック状の毛で他の植物に絡む。春先に多く出現。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Chenopodium giganteum",
    description: "高温乾燥に強く、栄養豊富な土壌に繁茂する大型雑草。",
    image_url: "",
  },
  {
    name: "ネズミムギ",
    scientific_name: "Lolium multiflorum",
    description: "牧草としても使われるが、雑草として定着した。",
    image_url: "",
  },
  {
    name: "スズメノテッポウ",
    scientific_name: "Echinochloa crus-galli",
    description: "イネ科の一年草。水田や畑でよく見られる雑草。",
    image_url: "",
  },
  {
    name: "カラスムギ",
    scientific_name: "Avena fatua",
    description: "ヨーロッパ原産の一年草。穂は羽毛状で風で飛散しやすい。",
    image_url: "",
  },
  {
    name: "カモジグサ",
    scientific_name: "Setaria viridis",
    description: "夏に茎が太くなるイネ科の雑草。畑の作物と競合する。",
    image_url: "",
  },
  {
    name: "ヒエ",
    scientific_name: "Echinochloa oryzicola",
    description: "水田の雑草として有名。穂が密集しているのが特徴。",
    image_url: "",
  },
  {
    name: "シロツメクサ",
    scientific_name: "Trifolium repens",
    description: "マメ科の多年草。芝地や道端で見られる白い花が特徴。",
    image_url: "",
  },
  {
    name: "オヒシバ",
    scientific_name: "Paspalum distichum",
    description: "湿った場所を好むイネ科の多年草。葉は幅広い。",
    image_url: "",
  },
  {
    name: "カタヒバリ",
    scientific_name: "Digitaria ciliaris var. okinawensis",
    description: "メヒシバの変種。沖縄など暖かい地域に多い。",
    image_url: "",
  },
  {
    name: "ヒメムカシヨモギ",
    scientific_name: "Artemisia indica var. maximowiczii",
    description: "春から夏にかけて黄色い花をつける多年草。",
    image_url: "",
  },
  {
    name: "ヒロハノカワラサイコ",
    scientific_name: "Galinsoga parviflora",
    description: "小さな白い花を咲かせる一年草。道端や畑に多い。",
    image_url: "",
  },
  {
    name: "ヒルムシロ",
    scientific_name: "Egeria densa",
    description: "水中に生育する多年草。水田の害草として知られる。",
    image_url: "",
  },
  {
    name: "ミズオオバコ",
    scientific_name: "Alisma plantago-aquatica",
    description: "水辺に生える多年草。根茎は湿地に適応。",
    image_url: "",
  },
  {
    name: "オオバナノエンレイソウ",
    scientific_name: "Trillium tschonoskii",
    description: "山地に生える多年草。大きな三枚の葉が特徴。",
    image_url: "",
  },
  {
    name: "キクイモモドキ",
    scientific_name: "Helianthus tuberosus var. subramosus",
    description: "ヒマワリに似た花を咲かせる多年草。畑で繁茂することも。",
    image_url: "",
  },
  {
    name: "ホソバワダン",
    scientific_name: "Polygonum aviculare var. depressum",
    description: "道端に生える一年草。葉が細長い。",
    image_url: "",
  },
  {
    name: "クサネム",
    scientific_name: "Sesbania cannabina",
    description: "マメ科の一年草。夏に黄色い花を咲かせる。",
    image_url: "",
  },
  {
    name: "イヌムギ",
    scientific_name: "Elymus repens",
    description: "多年草で地下茎により拡散。畑や道端に多い。",
    image_url: "",
  },
  {
    name: "ヤブカラシ",
    scientific_name: "Cayratia japonica",
    description: "つる性の多年草。繁殖力が強く、他の植物に絡みつく。",
    image_url: "",
  },
  {
    name: "ヒメツルソバ",
    scientific_name: "Polygonum capitatum",
    description: "地面を這うように広がる多年草。赤い花を咲かせる。",
    image_url: "",
  },
  {
    name: "アレチヌスビトハギ",
    scientific_name: "Desmodium canadense",
    description: "マメ科の多年草。種子が衣服に付着しやすい。",
    image_url: "",
  },
  {
    name: "オオイヌノフグリ",
    scientific_name: "Veronica persica",
    description: "青い小花を咲かせる春の雑草。道端や畑に多い。",
    image_url: "",
  },
  {
    name: "オオイヌノフグリ",
    scientific_name: "Veronica persica",
    description: "青い小さな花を咲かせる春の雑草。道端や畑でよく見られる。",
    image_url: "",
  },
  {
    name: "コニシキソウ",
    scientific_name: "Euphorbia maculata",
    description: "低く這うように広がる一年草。小さな赤い斑点が特徴。",
    image_url: "",
  },
  {
    name: "スズメノカタビラ",
    scientific_name: "Poa annua",
    description: "芝地や道端に生える小型の一年草。葉は柔らかい。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "キク科の多年草。白い花びらと黄色い中心が特徴。",
    image_url: "",
  },
  {
    name: "セイタカアワダチソウ",
    scientific_name: "Solidago altissima",
    description: "背の高い多年草。秋に黄色い花を密集して咲かせる。",
    image_url: "",
  },
  {
    name: "タチイヌノフグリ",
    scientific_name: "Veronica arvensis",
    description: "小型の一年草。青い小花が特徴で、畑や道端に生える。",
    image_url: "",
  },
  {
    name: "イヌホオズキ",
    scientific_name: "Solanum nigrum",
    description: "ナス科の一年草。小さな黒い実をつける雑草。",
    image_url: "",
  },
  {
    name: "ドクダミ",
    scientific_name: "Houttuynia cordata",
    description: "独特の匂いを持つ多年草。湿った場所に多く見られる。",
    image_url: "",
  },
  {
    name: "ヤブジラミ",
    scientific_name: "Torilis japonica",
    description: "セリ科の一年草。葉が細かく切れ込んでいるのが特徴。",
    image_url: "",
  },
  {
    name: "シロザ",
    scientific_name: "Chenopodium album",
    description: "多年草で畑や道端に多い。葉は三角形に近い。",
    image_url: "",
  },
  {
    name: "ヒルガオ",
    scientific_name: "Calystegia sepium",
    description: "つる性の多年草。朝に白や薄ピンクの花を咲かせる。",
    image_url: "",
  },
  {
    name: "ハコベ",
    scientific_name: "Stellaria media",
    description: "小さな白い花を持つ一年草。畑の害草として知られる。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago major",
    description: "道端や芝地に生える多年草。広い葉が特徴。",
    image_url: "",
  },
  {
    name: "スギナ",
    scientific_name: "Equisetum arvense",
    description: "地下茎で広がるシダ植物。春に細長い茎を出す。",
    image_url: "",
  },
  {
    name: "セリ",
    scientific_name: "Oenanthe javanica",
    description: "水辺に生える多年草。香りが強い。",
    image_url: "",
  },
  {
    name: "ハルジオン",
    scientific_name: "Erigeron philadelphicus",
    description: "ヒメジョオンに似るが花びらが細長い多年草。",
    image_url: "",
  },
  {
    name: "ヤブカンゾウ",
    scientific_name: "Hemerocallis fulva",
    description: "多年草で鮮やかなオレンジ色の花を咲かせる。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Amaranthus retroflexus",
    description: "一年草で高さがあり、赤い茎が特徴。",
    image_url: "",
  },
  {
    name: "ホトケノザ",
    scientific_name: "Lamium amplexicaule",
    description: "春に紫色の小花を咲かせる多年草。畑や道端に多い。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium aparine",
    description: "つる性の一年草。茎や葉に細かい刺がある。",
    image_url: "",
  },
  {
    name: "スイバ",
    scientific_name: "Rumex acetosa",
    description: "多年草で酸っぱい味が特徴。草地や道端に生える。",
    image_url: "",
  },
  {
    name: "コバンソウ",
    scientific_name: "Melica ciliata",
    description: "細長い穂をつける多年草のイネ科植物。芝地に多い。",
    image_url: "",
  },
  {
    name: "コマツヨイグサ",
    scientific_name: "Oenothera biennis",
    description: "黄色い花を夜に咲かせる多年草。畑の雑草。",
    image_url: "",
  },
  {
    name: "アメリカセンダングサ",
    scientific_name: "Bidens pilosa",
    description: "トゲトゲの種子が衣服に付く一年草。",
    image_url: "",
  },
  {
    name: "イヌタデ",
    scientific_name: "Persicaria longiseta",
    description: "赤みを帯びた茎を持つ一年草。畑や水辺に多い。",
    image_url: "",
  },
  {
    name: "ツユクサ",
    scientific_name: "Commelina communis",
    description: "青い花をつけるつる性の多年草。湿った場所に生える。",
    image_url: "",
  },
  {
    name: "カラスノエンドウ",
    scientific_name: "Vicia sativa",
    description: "つる性の一年草。紫色の花を咲かせる。",
    image_url: "",
  },
  {
    name: "アカツメクサ",
    scientific_name: "Trifolium pratense",
    description: "赤紫色の花をつける多年草。牧草としても使われる。",
    image_url: "",
  },
  {
    name: "ヒメツルソバ",
    scientific_name: "Polygonum capitatum",
    description: "小さなピンクの花をつけるつる性の多年草。",
    image_url: "",
  },
  {
    name: "シロツメクサ",
    scientific_name: "Trifolium repens",
    description: "白い花を咲かせる多年草。芝地によく生える。",
    image_url: "",
  },
  {
    name: "オヒシバ",
    scientific_name: "Digitaria ciliaris",
    description: "イネ科の一年草。広範囲に広がりやすい。",
    image_url: "",
  },
  {
    name: "メヒシバ",
    scientific_name: "Echinochloa crus-galli",
    description: "イネ科の一年草。稲作の害草として知られる。",
    image_url: "",
  },
  {
    name: "チチコグサ",
    scientific_name: "Gnaphalium affine",
    description: "小型の多年草。白っぽい葉が特徴。",
    image_url: "",
  },
  {
    name: "コセンダングサ",
    scientific_name: "Bidens frondosa",
    description: "アメリカセンダングサに似る一年草。種子にトゲがある。",
    image_url: "",
  },
  {
    name: "カワラケツメイ",
    scientific_name: "Cassia tora",
    description: "豆科の一年草。黄色い花をつける。",
    image_url: "",
  },
  {
    name: "ノゲシ",
    scientific_name: "Sonchus oleraceus",
    description: "キク科の多年草。黄色い花が特徴。",
    image_url: "",
  },
  {
    name: "オオアレチノギク",
    scientific_name: "Erigeron annuus",
    description: "ヒメジョオンと似ている多年草。やや大型。",
    image_url: "",
  },
  {
    name: "ヒナゲシ",
    scientific_name: "Papaver rhoeas",
    description: "赤い花を咲かせる一年草。畑や道端に生える。",
    image_url: "",
  },
  {
    name: "クズ",
    scientific_name: "Pueraria montana",
    description: "つる性の多年草。根は強力な根固めに使われる。",
    image_url: "",
  },
  {
    name: "ヤマノイモ",
    scientific_name: "Dioscorea japonica",
    description: "つる性の多年草。山地の林縁などに生える。",
    image_url: "",
  },
  {
    name: "カラスムギ",
    scientific_name: "Avena fatua",
    description: "一年草でイネ科。穂がふさふさしている。",
    image_url: "",
  },
  {
    name: "オオバコモドキ",
    scientific_name: "Plantago asiatica",
    description: "オオバコに似た多年草。湿った場所に生える。",
    image_url: "",
  },
  {
    name: "ヒメヒマワリ",
    scientific_name: "Eclipta prostrata",
    description: "小型のキク科多年草。湿地に多い。",
    image_url: "",
  },
  {
    name: "アキノノゲシ",
    scientific_name: "Sonchus asper",
    description: "キク科の多年草。トゲが多く葉が荒い。",
    image_url: "",
  },
  {
    name: "イヌガラシ",
    scientific_name: "Barbarea vulgaris",
    description: "アブラナ科の多年草。黄色い花が咲く。",
    image_url: "",
  },
  {
    name: "ホソバアカザ",
    scientific_name: "Amaranthus viridis",
    description: "一年草で茎が細いアカザの仲間。",
    image_url: "",
  },
  {
    name: "シナガワハギ",
    scientific_name: "Lespedeza cuneata",
    description: "マメ科の多年草。黄色い花を咲かせる。",
    image_url: "",
  },
  {
    name: "オオイヌノフグリモドキ",
    scientific_name: "Veronica arvensis",
    description: "オオイヌノフグリに似た小型の一年草。",
    image_url: "",
  },
  {
    name: "アシタバ",
    scientific_name: "Angelica keiskei",
    description: "セリ科の多年草。葉や茎が食用にされる。",
    image_url: "",
  },
  {
    name: "クルマバザクロソウ",
    scientific_name: "Phytolacca americana",
    description: "大型の多年草。紫黒色の実をつける。",
    image_url: "",
  },
  {
    name: "ヒメジョオンモドキ",
    scientific_name: "Erigeron philadelphicus",
    description: "ヒメジョオンに似た多年草。",
    image_url: "",
  },
  {
    name: "オランダミミナグサ",
    scientific_name: "Stellaria media",
    description: "小型の一年草。白い花をつける。",
    image_url: "",
  },
  {
    name: "イヌトウバナ",
    scientific_name: "Leonurus japonicus",
    description: "シソ科の多年草。小さな紫色の花を咲かせる。",
    image_url: "",
  },
  {
    name: "ムラサキツユクサ",
    scientific_name: "Commelina communis",
    description: "青紫色の花をつけるつる性多年草。",
    image_url: "",
  },
  {
    name: "カナムグラ",
    scientific_name: "Humulus japonicus",
    description: "つる性の一年草。茎や葉に毛が多い。",
    image_url: "",
  },
  {
    name: "コカラスムギ",
    scientific_name: "Avena strigosa",
    description: "イネ科の一年草。カラスムギに似る。",
    image_url: "",
  },
  {
    name: "カタバミ",
    scientific_name: "Oxalis corniculata",
    description: "多年草。葉が三つ葉で黄色い花を咲かせる。",
    image_url: "",
  },
  {
    name: "トキワハゼ",
    scientific_name: "Mazus pumilus",
    description: "小型の一年草。紫色の花が特徴。",
    image_url: "",
  },
  {
    name: "オオイヌノフグリ",
    scientific_name: "Veronica persica",
    description: "青い小さな花を咲かせる春の雑草。",
    image_url: "",
  },
  {
    name: "ヤブカンゾウ",
    scientific_name: "Hemerocallis fulva",
    description: "多年草で鮮やかなオレンジ色の花を咲かせる。",
    image_url: "",
  },
  {
    name: "オオアワガエリ",
    scientific_name: "Apera spica-venti",
    description: "イネ科の一年草。風に揺れる穂が特徴的。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Amaranthus retroflexus",
    description: "赤みがかった茎を持つ一年草。葉は食用にも。",
    image_url: "",
  },
  {
    name: "キツネノマゴ",
    scientific_name: "Justicia procumbens",
    description: "小型のシソ科多年草。紫色の花を咲かせる。",
    image_url: "",
  },
  {
    name: "コメツブツメクサ",
    scientific_name: "Trifolium dubium",
    description: "小さな黄色い花をつける多年草。芝地に多い。",
    image_url: "",
  },
  {
    name: "オオカワヂシャ",
    scientific_name: "Rorippa indica",
    description: "アブラナ科の多年草。湿った場所に生える。",
    image_url: "",
  },
  {
    name: "タチイヌノフグリ",
    scientific_name: "Veronica arvensis",
    description: "オオイヌノフグリに似るが小型の一年草。",
    image_url: "",
  },
  {
    name: "シロザ",
    scientific_name: "Chenopodium album",
    description: "一年草。肥沃な土壌によく生える。",
    image_url: "",
  },
  {
    name: "ミズヒキ",
    scientific_name: "Persicaria filiformis",
    description: "紅白の小さな花を咲かせる多年草。",
    image_url: "",
  },
  {
    name: "ヒメオドリコソウ",
    scientific_name: "Lamium purpureum",
    description: "シソ科の多年草。紫色の花が咲く。",
    image_url: "",
  },
  {
    name: "ホトケノザ",
    scientific_name: "Lamium amplexicaule",
    description: "春先に咲く赤紫色の花。多年草。",
    image_url: "",
  },
  {
    name: "スズメノエンドウ",
    scientific_name: "Vicia hirsuta",
    description: "つる性の一年草。小さな紫色の花が咲く。",
    image_url: "",
  },
  {
    name: "ミヤコグサ",
    scientific_name: "Lespedeza cuneata",
    description: "マメ科の多年草。黄色い花をつける。",
    image_url: "",
  },
  {
    name: "ヤハズエンドウ",
    scientific_name: "Vicia tetrasperma",
    description: "小型のつる性一年草。花は淡紫色。",
    image_url: "",
  },
  {
    name: "ヤブツルアズキ",
    scientific_name: "Vigna angularis var. nipponensis",
    description: "マメ科のつる性多年草。赤い豆がなる。",
    image_url: "",
  },
  {
    name: "イヌホオズキ",
    scientific_name: "Solanum nigrum",
    description: "ナス科の一年草。黒い実がなる。",
    image_url: "",
  },
  {
    name: "アキノタムラソウ",
    scientific_name: "Leonurus japonicus",
    description: "シソ科の多年草。秋に紫色の花を咲かせる。",
    image_url: "",
  },
  {
    name: "コセンダングサ",
    scientific_name: "Bidens frondosa",
    description: "一年草で種子にトゲがある。衣服に付着しやすい。",
    image_url: "",
  },
  {
    name: "オニノゲシ",
    scientific_name: "Sonchus asper",
    description: "キク科の多年草。大きな葉にトゲがある。",
    image_url: "",
  },
  {
    name: "ノアザミ",
    scientific_name: "Cirsium japonicum",
    description: "キク科の多年草。紫色の花が咲く。",
    image_url: "",
  },
  {
    name: "ハルジオン",
    scientific_name: "Erigeron philadelphicus",
    description: "ヒメジョオンに似た多年草。春に花を咲かせる。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago major",
    description: "葉が広く地面に広がる多年草。踏まれても強い。",
    image_url: "",
  },
  {
    name: "ツユクサ",
    scientific_name: "Commelina communis",
    description: "青い三枚花弁の一年草。湿った場所に多い。",
    image_url: "",
  },
  {
    name: "スギナ",
    scientific_name: "Equisetum arvense",
    description: "根茎を持つ多年草。繁殖力が強い。",
    image_url: "",
  },
  {
    name: "シロツメクサ",
    scientific_name: "Trifolium repens",
    description: "白い花を咲かせる多年草。芝生にもよく使われる。",
    image_url: "",
  },
  {
    name: "カタバミ",
    scientific_name: "Oxalis corniculata",
    description: "葉がクローバーのような形の多年草。酸味がある。",
    image_url: "",
  },
  {
    name: "オオイヌノフグリ",
    scientific_name: "Veronica persica",
    description: "青紫色の小花をつける一年草。春先に多い。",
    image_url: "",
  },
  {
    name: "ハコベ",
    scientific_name: "Stellaria media",
    description: "小さな白い花が咲く一年草。繁殖が早い。",
    image_url: "",
  },
  {
    name: "コニシキソウ",
    scientific_name: "Euphorbia maculata",
    description: "地面に這う一年草。葉に赤い斑点がある。",
    image_url: "",
  },
  {
    name: "ギシギシ",
    scientific_name: "Rumex acetosa",
    description: "多年草で酸味のある葉を持つ。繁殖力強い。",
    image_url: "",
  },
  {
    name: "ヤブカラシ",
    scientific_name: "Cayratia japonica",
    description: "つる性の多年草。勢いよく他の植物に絡みつく。",
    image_url: "",
  },
  {
    name: "スイバ",
    scientific_name: "Rumex acetosella",
    description: "酸味のある小型の多年草。草地に多い。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "春から初夏にかけて白い花を咲かせる多年草。",
    image_url: "",
  },
  {
    name: "ツルムラサキ",
    scientific_name: "Basella alba",
    description: "つる性の野菜兼雑草。葉は食用。",
    image_url: "",
  },
  {
    name: "ミズバショウ",
    scientific_name: "Lysichiton camtschatcensis",
    description: "湿地に生える多年草。白い花が特徴的。",
    image_url: "",
  },
  {
    name: "アメリカセンダングサ",
    scientific_name: "Bidens pilosa",
    description: "トゲのある種子が衣服に付く一年草。",
    image_url: "",
  },
  {
    name: "オオキンケイギク",
    scientific_name: "Coreopsis lanceolata",
    description: "鮮やかな黄色の花を咲かせる多年草。",
    image_url: "",
  },
  {
    name: "ヒルガオ",
    scientific_name: "Calystegia japonica",
    description: "つる性の多年草。朝顔に似た花を咲かせる。",
    image_url: "",
  },
  {
    name: "マツバウンラン",
    scientific_name: "Linaria vulgaris",
    description: "黄色い花を咲かせる多年草。繁殖力が強い。",
    image_url: "",
  },
  {
    name: "シロザ",
    scientific_name: "Chenopodium album",
    description: "多年草で肥沃な土壌に多い。雑草として有名。",
    image_url: "",
  },
  {
    name: "セイタカアワダチソウ",
    scientific_name: "Solidago altissima",
    description: "背が高く黄色い花をつける多年草。群生しやすい。",
    image_url: "",
  },
  {
    name: "オオブタクサ",
    scientific_name: "Ambrosia trifida",
    description: "大型の一年草。花粉症の原因となることもある。",
    image_url: "",
  },
  {
    name: "コセンダングサ",
    scientific_name: "Bidens ferulifolia",
    description: "黄色い小花が密集する一年草。衣服に種子が付く。",
    image_url: "",
  },
  {
    name: "クサネム",
    scientific_name: "Sesbania cannabina",
    description: "つる性の一年草。土壌改良にも使われる。",
    image_url: "",
  },
  {
    name: "ミズヒキ",
    scientific_name: "Persicaria longiseta",
    description: "赤と白の小さな花をつける多年草。湿地に多い。",
    image_url: "",
  },
  {
    name: "イヌホオズキ",
    scientific_name: "Solanum nigrum",
    description: "黒い実をつける一年草。毒性あり注意が必要。",
    image_url: "",
  },
  {
    name: "ヒルザキツキミソウ",
    scientific_name: "Oenothera speciosa",
    description: "ピンクの花を咲かせる多年草。庭にも植えられる。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Amaranthus retroflexus",
    description: "背が高くなる一年草。種子が多く繁殖力強い。",
    image_url: "",
  },
  {
    name: "ススキ",
    scientific_name: "Miscanthus sinensis",
    description: "秋に穂をつける多年草。草地でよく見かける。",
    image_url: "",
  },
  {
    name: "キクイモ",
    scientific_name: "Helianthus tuberosus",
    description: "黄色い花を咲かせる多年草。地下茎で増える。",
    image_url: "",
  },
  {
    name: "コバンソウ",
    scientific_name: "Melica ciliata",
    description: "小穂が特徴的な多年草。芝生に混入することも。",
    image_url: "",
  },
  {
    name: "アキノタムラソウ",
    scientific_name: "Scutellaria indica",
    description: "紫色の花が特徴的な多年草。山地に生育。",
    image_url: "",
  },
  {
    name: "ヤブジラミ",
    scientific_name: "Anthriscus sylvestris",
    description: "白い花を咲かせる多年草。葉はシダのよう。",
    image_url: "",
  },
  {
    name: "オオイヌノフグリ（変種）",
    scientific_name: "Veronica persica var. minor",
    description: "オオイヌノフグリの小型変種。春先に見られる。",
    image_url: "",
  },
  {
    name: "ノゲシ",
    scientific_name: "Sonchus oleraceus",
    description: "黄色い花が咲く一年草。繁殖力が強い。",
    image_url: "",
  },
  {
    name: "タネツケバナ",
    scientific_name: "Rorippa indica",
    description: "水田周辺に多い小型の一年草。早春に開花。",
    image_url: "",
  },
  {
    name: "ヒメムカシヨモギ",
    scientific_name: "Artemisia princeps var. orientalis",
    description: "香りのある多年草。ヨモギの変種。",
    image_url: "",
  },
  {
    name: "フユノハナワラビ",
    scientific_name: "Polystichum acrostichoides",
    description: "冬にも緑を保つシダ植物。多年草。",
    image_url: "",
  },
  {
    name: "クサフジ",
    scientific_name: "Vicia sativa",
    description: "つる性の一年草。豆科で土壌改良に利用。",
    image_url: "",
  },
  {
    name: "シラヤマギク",
    scientific_name: "Aster yomena",
    description: "白い花を咲かせる多年草。山地に自生。",
    image_url: "",
  },
  {
    name: "カラスムギ",
    scientific_name: "Avena fatua",
    description: "雑草性のイネ科多年草。農地の害草として知られる。",
    image_url: "",
  },
  {
    name: "ツリガネニンジン",
    scientific_name: "Codonopsis lanceolata",
    description: "鐘形の青紫の花を咲かせる多年草。山野に自生。",
    image_url: "",
  },
  {
    name: "ノアザミ",
    scientific_name: "Cirsium japonicum",
    description: "トゲのある葉と紫色の花を持つ多年草。薬用にも。",
    image_url: "",
  },
  {
    name: "カワラナデシコ",
    scientific_name: "Dianthus superbus",
    description: "ピンクの細長い花を咲かせる多年草。乾燥地に多い。",
    image_url: "",
  },
  {
    name: "ヤマブキ",
    scientific_name: "Kerria japonica",
    description: "黄色い花を咲かせる低木。庭木としても人気。",
    image_url: "",
  },
  {
    name: "ノコンギク",
    scientific_name: "Aster ageratoides",
    description: "紫色の花を咲かせる多年草。秋に見られる。",
    image_url: "",
  },
  {
    name: "シラヤマギク",
    scientific_name: "Aster yomena",
    description: "白い花を咲かせる多年草。山地の草原に多い。",
    image_url: "",
  },
  {
    name: "カントウタンポポ",
    scientific_name: "Taraxacum platycarpum",
    description: "日本固有種のタンポポ。黄色い花が特徴。",
    image_url: "",
  },
  {
    name: "ヒメオドリコソウ",
    scientific_name: "Lamium purpureum",
    description: "小さな紫色の花を咲かせる多年草。春先に見られる。",
    image_url: "",
  },
  {
    name: "シソ",
    scientific_name: "Perilla frutescens",
    description: "香りのある一年草。葉は料理に使われる。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago major",
    description: "葉が広く地面に広がる多年草。踏まれても強い。",
    image_url: "",
  },
  {
    name: "ヒメジソ",
    scientific_name: "Perilla frutescens var. crispa",
    description: "シソの変種。葉が縮れている。",
    image_url: "",
  },
  {
    name: "ヤブマオ",
    scientific_name: "Urera laciniata",
    description: "低木性の多年草。葉が大きく繁茂する。",
    image_url: "",
  },
  {
    name: "オオバコモドキ",
    scientific_name: "Plantago asiatica",
    description: "オオバコに似る多年草。葉は狭い。",
    image_url: "",
  },
  {
    name: "コアカザ",
    scientific_name: "Amaranthus cruentus",
    description: "アカザの一種。鮮やかな赤い葉を持つ。",
    image_url: "",
  },
  {
    name: "ヒメシロザ",
    scientific_name: "Chenopodium murale",
    description: "シロザに似る小型の一年草。庭に多い。",
    image_url: "",
  },
  {
    name: "シラヤマギク（変種）",
    scientific_name: "Aster yomena var. maximowiczii",
    description: "シラヤマギクの変種。花がやや大きい。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "春から初夏にかけて白い花を咲かせる多年草。",
    image_url: "",
  },
  {
    name: "オオイヌノフグリ",
    scientific_name: "Veronica persica",
    description: "青紫色の小花をつける一年草。春先に多い。",
    image_url: "",
  },
  {
    name: "カラスムギ",
    scientific_name: "Avena fatua",
    description: "雑草性のイネ科多年草。農地の害草として知られる。",
    image_url: "",
  },
  {
    name: "セイタカアワダチソウ",
    scientific_name: "Solidago altissima",
    description: "背が高く黄色い花をつける多年草。群生しやすい。",
    image_url: "",
  },
  {
    name: "コセンダングサ",
    scientific_name: "Bidens pilosa var. radiata",
    description: "黄色い花ととげとげしい実を持つ一年草。衣服に付きやすい。",
    image_url: "",
  },
  {
    name: "アレチヌスビトハギ",
    scientific_name: "Desmodium paniculatum",
    description: "秋に紫の小花を咲かせるマメ科の多年草。繁殖力が強い。",
    image_url: "",
  },
  {
    name: "クサギ",
    scientific_name: "Clerodendrum trichotomum",
    description: "独特の臭いがある低木。赤いがくと青い実が特徴。",
    image_url: "",
  },
  {
    name: "アキノキリンソウ",
    scientific_name: "Solidago virgaurea",
    description: "秋に黄色い花を咲かせる多年草。山地に自生。",
    image_url: "",
  },
  {
    name: "キランソウ",
    scientific_name: "Ajuga decumbens",
    description: "地面を這うように広がる多年草。紫の小花を咲かせる。",
    image_url: "",
  },
  {
    name: "ツルニチニチソウ",
    scientific_name: "Vinca major",
    description: "つる性の多年草。紫青色の花が特徴で、グランドカバーに利用される。",
    image_url: "",
  },
  {
    name: "カナムグラ",
    scientific_name: "Humulus scandens",
    description: "つる性の一年草で、荒地に群生する。繁殖力が強い。",
    image_url: "",
  },
  {
    name: "ミゾソバ",
    scientific_name: "Persicaria thunbergii",
    description: "湿地に多く、ピンクの小さな花を咲かせる一年草。",
    image_url: "",
  },
  {
    name: "アキノウナギツカミ",
    scientific_name: "Persicaria sieboldii",
    description: "水辺に生える一年草。茎に小さなトゲがある。",
    image_url: "",
  },
  {
    name: "ヌスビトハギ",
    scientific_name: "Desmodium podocarpum",
    description: "マメ科の多年草で、実が衣服に付きやすい。秋に花が咲く。",
    image_url: "",
  },
  {
    name: "クズ",
    scientific_name: "Pueraria lobata",
    description: "つる性の多年草で、根は薬用や食品にも使われる。繁殖力旺盛。",
    image_url: "",
  },
  {
    name: "メヒシバ",
    scientific_name: "Digitaria ciliaris",
    description: "地面を這うように広がるイネ科の一年草。踏みつけに強い。",
    image_url: "",
  },
  {
    name: "イヌビエ",
    scientific_name: "Echinochloa crus-galli",
    description: "水田などに発生するイネ科の一年草。農業雑草として有名。",
    image_url: "",
  },
  {
    name: "チガヤ",
    scientific_name: "Imperata cylindrica",
    description: "地下茎で広がる多年草。白い穂を出す。草原や堤防に多い。",
    image_url: "",
  },
  {
    name: "スズメノカタビラ",
    scientific_name: "Poa annua",
    description: "芝地や道端に多いイネ科の一年草。冬にも見られる。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium spurium",
    description: "細い茎が絡まりやすい一年草。手にくっつく種を持つ。",
    image_url: "",
  },
  {
    name: "オオチドメ",
    scientific_name: "Hydrocotyle sibthorpioides",
    description: "湿った地面を這って広がる多年草。小さな円形の葉が特徴。",
    image_url: "",
  },
  {
    name: "ムラサキサギゴケ",
    scientific_name: "Mazus miquelii",
    description: "紫の花を咲かせる多年草。日陰や湿地に生える。",
    image_url: "",
  },
  {
    name: "ツユクサ",
    scientific_name: "Commelina communis",
    description: "鮮やかな青い花を咲かせる一年草。朝に咲いて昼にはしぼむ。",
    image_url: "",
  },
  {
    name: "ハコベ",
    scientific_name: "Stellaria media",
    description: "春の七草の一つ。小さな白い花を咲かせる多年草。",
    image_url: "",
  },
  {
    name: "オオジシバリ",
    scientific_name: "Ixeris debilis",
    description: "黄色いタンポポに似た花を咲かせる多年草。道端などに生育。",
    image_url: "",
  },
  {
    name: "シロバナタンポポ",
    scientific_name: "Taraxacum albidum",
    description: "白い花を咲かせる日本固有のタンポポの一種。西日本に多い。",
    image_url: "",
  },
  {
    name: "イヌガラシ",
    scientific_name: "Rorippa indica",
    description: "黄色い小花を咲かせるアブラナ科の一年草。湿地を好む。",
    image_url: "",
  },
  {
    name: "ハルジオン",
    scientific_name: "Erigeron philadelphicus",
    description: "白や薄紫の細い花びらが特徴。北アメリカ原産の帰化植物。",
    image_url: "",
  },
  {
    name: "アメリカセンダングサ",
    scientific_name: "Bidens frondosa",
    description: "とげとげの実が衣服にくっつく。河川敷に多い帰化植物。",
    image_url: "",
  },
  {
    name: "アキノタムラソウ",
    scientific_name: "Salvia japonica",
    description: "秋に青紫色の花を咲かせる多年草。シソ科で香りがある。",
    image_url: "",
  },
  {
    name: "スベリヒユ",
    scientific_name: "Portulaca oleracea",
    description: "多肉質の茎葉を持つ一年草。食用にもなる。",
    image_url: "",
  },
  {
    name: "コニシキソウ",
    scientific_name: "Euphorbia supina",
    description: "地面を這う一年草。茎を折ると白い液が出る。",
    image_url: "",
  },
  {
    name: "ノゲシ",
    scientific_name: "Sonchus oleraceus",
    description: "タンポポに似た黄色い花を咲かせる一年草。やわらかい葉を持つ。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "ハルジオンに似ているが、茎が中空でなくしっかりしている。",
    image_url: "",
  },
  {
    name: "ハハコグサ",
    scientific_name: "Gnaphalium affine",
    description: "春の七草の一つ。白い綿毛に包まれた花を咲かせる。",
    image_url: "",
  },
  {
    name: "セイタカアワダチソウ",
    scientific_name: "Solidago altissima",
    description: "秋に黄色い花を穂状に咲かせる多年草。アレロパシー作用あり。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Chenopodium album",
    description: "白っぽい粉を帯びた葉を持つ一年草。畑などに多い。",
    image_url: "",
  },
  {
    name: "ホトケノザ",
    scientific_name: "Lamium amplexicaule",
    description: "春の七草ではない方のホトケノザ。紫の唇形花を持つ。",
    image_url: "",
  },
  {
    name: "カタバミ",
    scientific_name: "Oxalis corniculata",
    description: "黄色い花を咲かせる多年草。三つ葉がクローバーに似る。",
    image_url: "",
  },
  {
    name: "オランダミミナグサ",
    scientific_name: "Cerastium glomeratum",
    description: "白い花を咲かせるナデシコ科の一年草。帰化植物。",
    image_url: "",
  },
  {
    name: "トキワハゼ",
    scientific_name: "Mazus pumilus",
    description: "地面を這うように広がる一年草。紫色の小さな花をつける。",
    image_url: "",
  },
  {
    name: "ハキダメギク",
    scientific_name: "Galinsoga quadriradiata",
    description: "白と黄色の小さな花を咲かせる。ゴミ捨て場に多く見られる。",
    image_url: "",
  },
  {
    name: "ミチヤナギ",
    scientific_name: "Polygonum aviculare",
    description: "踏みつけに強く、道端や校庭などに生える。",
    image_url: "",
  },
  {
    name: "イヌホオズキ",
    scientific_name: "Solanum nigrum",
    description: "ナス科の一年草。黒い実をつけるが毒がある場合も。",
    image_url: "",
  },
  {
    name: "メヒシバ",
    scientific_name: "Digitaria ciliaris",
    description: "夏によく見られるイネ科の一年草。地面を這うように伸びる。",
    image_url: "",
  },
  {
    name: "オヒシバ",
    scientific_name: "Eleusine indica",
    description: "道路や校庭などに多く見られるイネ科の強健な雑草。",
    image_url: "",
  },
  {
    name: "チドメグサ",
    scientific_name: "Hydrocotyle sibthorpioides",
    description: "地面を這う多年草。小さな丸い葉が特徴で、薬草としても知られる。",
    image_url: "",
  },
  {
    name: "ムラサキカタバミ",
    scientific_name: "Oxalis corymbosa",
    description: "紫色の花を咲かせる多年草。カタバミに似た葉を持つ帰化植物。",
    image_url: "",
  },
  {
    name: "ヘクソカズラ",
    scientific_name: "Paederia scandens",
    description: "独特な臭いを持つつる植物。白い縁のある小さな花を咲かせる。",
    image_url: "",
  },
  {
    name: "ヤブガラシ",
    scientific_name: "Cayratia japonica",
    description: "つるで覆うように繁茂する。他の植物に絡みつく多年草。",
    image_url: "",
  },
  {
    name: "ツユクサ",
    scientific_name: "Commelina communis",
    description: "青い美しい花を咲かせる一年草。朝咲いて昼にしぼむ。",
    image_url: "",
  },
  {
    name: "ドクダミ",
    scientific_name: "Houttuynia cordata",
    description: "白い花と強い臭いが特徴。薬草としても利用される多年草。",
    image_url: "",
  },
  {
    name: "ユウゲショウ",
    scientific_name: "Oenothera rosea",
    description: "ピンク色のかわいらしい花を咲かせる帰化植物。道端に多い。",
    image_url: "",
  },
  {
    name: "カラスノエンドウ",
    scientific_name: "Vicia sativa",
    description: "春に紫色の花を咲かせるマメ科のつる植物。実はさや状。",
    image_url: "",
  },
  {
    name: "スズメノカタビラ",
    scientific_name: "Poa annua",
    description: "イネ科の雑草で、非常に繁殖力が強く芝地にも出現する。",
    image_url: "",
  },
  {
    name: "セイヨウタンポポ",
    scientific_name: "Taraxacum officinale",
    description: "外来種のタンポポ。総苞片が反り返るのが特徴。",
    image_url: "",
  },
  {
    name: "アレチウリ",
    scientific_name: "Sicyos angulatus",
    description: "繁殖力の強いつる性植物で、鋭いトゲがある果実をつける。",
    image_url: "",
  },
  {
    name: "ミゾソバ",
    scientific_name: "Persicaria thunbergii",
    description: "湿地に多い一年草。ピンクの小花を球状に咲かせる。",
    image_url: "",
  },
  {
    name: "マメグンバイナズナ",
    scientific_name: "Lepidium virginicum",
    description: "白い小花とハート型の種が特徴的な帰化植物。",
    image_url: "",
  },
  {
    name: "ミズヒキ",
    scientific_name: "Persicaria filiformis",
    description: "赤と白の小さな花を穂状につける多年草。林縁や山地に生える。",
    image_url: "",
  },
  {
    name: "イタドリ",
    scientific_name: "Fallopia japonica",
    description: "大きな葉と赤味を帯びた茎が特徴。河原や空き地に繁茂。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium spurium",
    description: "触るとひっつく一年草。葉の縁に細かいとげがある。",
    image_url: "",
  },
  {
    name: "ネジバナ",
    scientific_name: "Spiranthes sinensis",
    description: "花が螺旋状に並ぶラン科の多年草。芝生などに自生。",
    image_url: "",
  },
  {
    name: "ヒガンバナ",
    scientific_name: "Lycoris radiata",
    description: "彼岸の時期に真っ赤な花を咲かせる多年草。毒性がある。",
    image_url: "",
  },
  {
    name: "ホトケノザ",
    scientific_name: "Lamium amplexicaule",
    description: "春先に紫色の唇形花をつけるシソ科の一年草。食用にもなる。",
    image_url: "",
  },
  {
    name: "ヒメオドリコソウ",
    scientific_name: "Lamium purpureum",
    description: "ホトケノザに似た外来の一年草。紫の花を咲かせる。",
    image_url: "",
  },
  {
    name: "コオニタビラコ",
    scientific_name: "Lapsana apogonoides",
    description: "タンポポに似た黄色い花を咲かせる一年草。春の七草の一つ「ほとけのざ」。",
    image_url: "",
  },
  {
    name: "ナズナ",
    scientific_name: "Capsella bursa-pastoris",
    description: "ハート型の果実が特徴。春の七草で「ぺんぺん草」とも呼ばれる。",
    image_url: "",
  },
  {
    name: "タビラコ",
    scientific_name: "Lapsana apogonoides",
    description: "小さなタンポポ状の花を咲かせる春の野草。ロゼット葉が特徴。",
    image_url: "",
  },
  {
    name: "カタバミ",
    scientific_name: "Oxalis corniculata",
    description: "黄色い花とハート形の葉。酸味があり、食用・薬用にも。",
    image_url: "",
  },
  {
    name: "シロザ",
    scientific_name: "Chenopodium album",
    description: "白っぽい粉をふいた葉が特徴のアカザ科の雑草。食用にもなる。",
    image_url: "",
  },
  {
    name: "アメリカセンダングサ",
    scientific_name: "Bidens frondosa",
    description: "ひっつき虫として知られる果実を持つ外来雑草。",
    image_url: "",
  },
  {
    name: "キランソウ",
    scientific_name: "Ajuga decumbens",
    description: "地面を這うように広がり、紫色の花を咲かせる多年草。",
    image_url: "",
  },
  {
    name: "カキドオシ",
    scientific_name: "Glechoma hederacea",
    description: "つる性で繁殖力が強い。春に青紫の花を咲かせる薬草。",
    image_url: "",
  },
  {
    name: "ヘビイチゴ",
    scientific_name: "Duchesnea chrysantha",
    description: "黄色い花を咲かせ、赤い偽果をつける。毒性はないが食用には向かない。",
    image_url: "",
  },
  {
    name: "ヤブジラミ",
    scientific_name: "Torilis japonica",
    description: "果実にかぎ状の毛があり、衣服にくっつく多年草。",
    image_url: "",
  },
  {
    name: "マツヨイグサ",
    scientific_name: "Oenothera biennis",
    description: "夕方に黄色い花を咲かせる外来植物。夜咲きで虫を引き寄せる。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago asiatica",
    description: "踏みつけに強い多年草。薬草として古くから親しまれている。",
    image_url: "",
  },
  {
    name: "スベリヒユ",
    scientific_name: "Portulaca oleracea",
    description: "地面を這う肉厚の茎葉が特徴。栄養価が高く食用にもなる。",
    image_url: "",
  },
  {
    name: "セリ",
    scientific_name: "Oenanthe javanica",
    description: "春の七草の一つ。水辺に群生し、香りが良い。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "細い白い花びらを持つキク科の帰化植物。夏に多く見られる。",
    image_url: "",
  },
  {
    name: "ナガミヒナゲシ",
    scientific_name: "Papaver dubium",
    description: "オレンジ色の花と細長い実が特徴の外来植物。",
    image_url: "",
  },
  {
    name: "ブタクサ",
    scientific_name: "Ambrosia artemisiifolia",
    description: "花粉症の原因植物の一つ。葉は羽状に深く切れ込む。",
    image_url: "",
  },
  {
    name: "セイタカアワダチソウ",
    scientific_name: "Solidago altissima",
    description: "黄色い花を円錐状に咲かせる大型の多年草。繁殖力が強い外来種。",
    image_url: "",
  },
  {
    name: "ハキダメギク",
    scientific_name: "Galinsoga ciliata",
    description: "ごみ捨て場によく生えることから名付けられた外来雑草。白い小花が特徴。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium spurium",
    description: "ザラつく茎と葉で衣類にひっつく一年草。春先に群生しやすい。",
    image_url: "",
  },
  {
    name: "メヒシバ",
    scientific_name: "Digitaria ciliaris",
    description: "芝のように地面を這い広がるイネ科雑草。夏に穂をつける。",
    image_url: "",
  },
  {
    name: "オヒシバ",
    scientific_name: "Eleusine indica",
    description: "太い茎と広い葉を持つイネ科の多年草。踏圧に強く、道端に多い。",
    image_url: "",
  },
  {
    name: "アメリカアゼナ",
    scientific_name: "Lindernia dubia",
    description: "湿地や水田に多く見られる外来種で、紫がかった小花が特徴。",
    image_url: "",
  },
  {
    name: "ウシハコベ",
    scientific_name: "Stellaria aquatica",
    description: "葉が大きく茎が太いハコベの仲間。水田や湿地に分布。",
    image_url: "",
  },
  {
    name: "スズメノカタビラ",
    scientific_name: "Poa annua",
    description: "イネ科の一年草で、寒い時期にも育つ丈夫な雑草。",
    image_url: "",
  },
  {
    name: "ヤブカラシ",
    scientific_name: "Cayratia japonica",
    description: "つる性で樹木やフェンスに絡みつく。別名「ビンボウカズラ」。",
    image_url: "",
  },
  {
    name: "アカバナユウゲショウ",
    scientific_name: "Oenothera rosea",
    description: "ピンク色の小花を咲かせる外来種。見た目は可憐だが繁殖力が高い。",
    image_url: "",
  },
  {
    name: "イヌガラシ",
    scientific_name: "Rorippa indica",
    description: "からし菜に似たアブラナ科の野草。黄色い小花が特徴。",
    image_url: "",
  },
  {
    name: "イヌビユ",
    scientific_name: "Amaranthus viridis",
    description: "葉が楕円形で先がとがるヒユ科の一年草。夏に群生する。",
    image_url: "",
  },
  {
    name: "エノコログサ",
    scientific_name: "Setaria viridis",
    description: "穂が猫のしっぽのように見えるため「ねこじゃらし」とも呼ばれる。",
    image_url: "",
  },
  {
    name: "コニシキソウ",
    scientific_name: "Euphorbia supina",
    description: "地面に這うように成長し、赤紫色の葉を持つ小さな雑草。",
    image_url: "",
  },
  {
    name: "ムラサキケマン",
    scientific_name: "Corydalis incisa",
    description: "春に紫色の筒状花をつける。ケシ科で毒性があるため注意が必要。",
    image_url: "",
  },
  {
    name: "ノゲシ",
    scientific_name: "Sonchus oleraceus",
    description: "タンポポに似た黄色い花を咲かせる。葉がトゲトゲしている。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Atriplex hortensis",
    description: "灰緑色の葉に白粉をふいたような姿。食用になる場合もある。",
    image_url: "",
  },
  {
    name: "アオビユ",
    scientific_name: "Amaranthus lividus",
    description: "ヒユ科の雑草。葉に赤紫色の斑点が入ることがある。",
    image_url: "",
  },
  {
    name: "コセンダングサ",
    scientific_name: "Bidens pilosa var. minor",
    description: "細かい実が服にくっつくことで知られる「ひっつき虫」。",
    image_url: "",
  },
  {
    name: "ナギナタコウジュ",
    scientific_name: "Elsholtzia ciliata",
    description: "秋にナギナタのような穂を出すシソ科の一年草。香りがある。",
    image_url: "",
  },
  {
    name: "キツネノボタン",
    scientific_name: "Ranunculus silerifolius",
    description: "黄色い5弁花をつけるキンポウゲ科の多年草。湿地に生える。",
    image_url: "",
  },
  {
    name: "ツボミオオバコ",
    scientific_name: "Plantago asiatica",
    description: "地面に広がるロゼット状の葉が特徴の多年草。踏みつけに強く道端に多い。",
    image_url: "",
  },
  {
    name: "ツユクサ",
    scientific_name: "Commelina communis",
    description: "青い三枚花弁の花を朝に咲かせる。日が昇るとしぼむ特性がある。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago major",
    description: "踏みつけに強く、車道や歩道にも見られる多年草。種は漢方に用いられる。",
    image_url: "",
  },
  {
    name: "マツヨイグサ",
    scientific_name: "Oenothera biennis",
    description: "夕方に黄色い花を咲かせる外来植物。別名「月見草」。",
    image_url: "",
  },
  {
    name: "ミゾソバ",
    scientific_name: "Persicaria thunbergii",
    description: "湿地に自生し、ピンクの小花を多数咲かせる。葉の形が特徴的。",
    image_url: "",
  },
  {
    name: "ヌスビトハギ",
    scientific_name: "Desmodium podocarpum",
    description: "マメ科の多年草。小花をつけ、果実は衣服にひっつく。",
    image_url: "",
  },
  {
    name: "アメリカセンダングサ",
    scientific_name: "Bidens frondosa",
    description: "ひっつき虫の代表格。直立した茎に黄花を咲かせる外来種。",
    image_url: "",
  },
  {
    name: "アレチヌスビトハギ",
    scientific_name: "Desmodium paniculatum",
    description: "ひっつき虫の一種で、細長い葉を持つ外来種。荒れ地に生える。",
    image_url: "",
  },
  {
    name: "ヤブマオ",
    scientific_name: "Boehmeria tricuspis",
    description: "イラクサ科の多年草。茎に毛が多く、背丈が高くなる。",
    image_url: "",
  },
  {
    name: "セイバンモロコシ",
    scientific_name: "Sorghum halepense",
    description: "イネ科の多年草。高く伸び、群落を形成する。外来雑草。",
    image_url: "",
  },
  {
    name: "シロツメクサ",
    scientific_name: "Trifolium repens",
    description: "クローバーの名で知られるマメ科草本。白い花を密につける。",
    image_url: "",
  },
  {
    name: "アカツメクサ",
    scientific_name: "Trifolium pratense",
    description: "ピンク〜赤紫色の丸い花が特徴。牧草や緑肥としても利用される。",
    image_url: "",
  },
  {
    name: "ハルジオン",
    scientific_name: "Erigeron philadelphicus",
    description: "春に咲くキク科植物。白い糸状の花びらが特徴で、外来種。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "ハルジオンに似るが茎が中空でない。夏に咲くキク科の雑草。",
    image_url: "",
  },
  {
    name: "ホトケノザ",
    scientific_name: "Lamium amplexicaule",
    description: "春の七草の一つと誤解されがちだが別種。紫色の花を咲かせる。",
    image_url: "",
  },
  {
    name: "ナズナ",
    scientific_name: "Capsella bursa-pastoris",
    description: "春の七草の一つ。ハート型の種子が特徴的なアブラナ科雑草。",
    image_url: "",
  },
  {
    name: "スベリヒユ",
    scientific_name: "Portulaca oleracea",
    description: "多肉質の葉と茎を持つ夏草。可食で栄養価が高いが繁殖力も強い。",
    image_url: "",
  },
  {
    name: "ハコベ",
    scientific_name: "Stellaria media",
    description: "春の七草にも含まれ、柔らかく可食。小さな白い花が咲く。",
    image_url: "",
  },
  {
    name: "タビラコ",
    scientific_name: "Lapsana apogonoides",
    description: "春の七草のホトケノザの別名。ロゼット状に広がる。",
    image_url: "",
  },
  {
    name: "オオジシバリ",
    scientific_name: "Ixeris debilis",
    description: "黄色い花を咲かせ、地面を這うように成長する多年草。",
    image_url: "",
  },
  {
    name: "カラスノエンドウ",
    scientific_name: "Vicia sativa",
    description: "春先に紫の花をつけるマメ科のつる植物。若芽は食用になることもある。",
    image_url: "",
  },
  {
    name: "スズメノエンドウ",
    scientific_name: "Vicia hirsuta",
    description: "カラスノエンドウに似るが、花が小さい。細かい葉と細いつるが特徴。",
    image_url: "",
  },
  {
    name: "ヤハズエンドウ",
    scientific_name: "Vicia angustifolia",
    description: "葉の先が矢筈形に凹むことからこの名がある。赤紫の花を咲かせる。",
    image_url: "",
  },
  {
    name: "ヒメオドリコソウ",
    scientific_name: "Lamium purpureum",
    description: "ヨーロッパ原産のシソ科雑草。紫色の葉と花が特徴。",
    image_url: "",
  },
  {
    name: "カタバミ",
    scientific_name: "Oxalis corniculata",
    description: "三つ葉と黄色い花を持つ。酸味があるため触るとわかりやすい。",
    image_url: "",
  },
  {
    name: "ムラサキツメクサ",
    scientific_name: "Trifolium pratense",
    description: "ピンクの花をつけるクローバーの仲間。マメ科で緑肥にもなる。",
    image_url: "",
  },
  {
    name: "アキノウナギツカミ",
    scientific_name: "Persicaria sagittata",
    description: "水辺に生えるタデ科植物。鋭いトゲで他の植物に絡みつく。",
    image_url: "",
  },
  {
    name: "コメツブツメクサ",
    scientific_name: "Trifolium dubium",
    description: "黄色い小さな花をつけるマメ科植物。芝地などに群生。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium spurium",
    description: "茎や葉に細かいトゲがあり衣服にひっつく。春に淡い花をつける。",
    image_url: "",
  },
  {
    name: "ウラジロチチコグサ",
    scientific_name: "Gamochaeta purpurea",
    description: "裏面が白っぽい葉を持つキク科雑草。ドライな場所に好んで生える。",
    image_url: "",
  },
  {
    name: "チチコグサ",
    scientific_name: "Gnaphalium affine",
    description: "春に白っぽい綿毛のような花を咲かせる多年草。葉は細長く密に生える。",
    image_url: "",
  },
  {
    name: "オニノゲシ",
    scientific_name: "Sonchus asper",
    description: "葉に大きなトゲがあるノゲシの仲間。キク科の一年草。",
    image_url: "",
  },
  {
    name: "オランダミミナグサ",
    scientific_name: "Cerastium glomeratum",
    description: "白く小さな花と毛深い茎葉をもつ外来種。春に群生しやすい。",
    image_url: "",
  },
  {
    name: "ナヨクサフジ",
    scientific_name: "Vicia villosa",
    description: "紫の花を穂状につけるつる性のマメ科植物。緑肥としても利用される。",
    image_url: "",
  },
  {
    name: "ホソアオゲイトウ",
    scientific_name: "Amaranthus spinosus",
    description: "茎にトゲがあり、繁殖力の強いヒユ科の一年草。外来種。",
    image_url: "",
  },
  {
    name: "アキノゲシ",
    scientific_name: "Lactuca indica",
    description: "秋に黄色いタンポポに似た花を咲かせる多年草。草丈が高い。",
    image_url: "",
  },
  {
    name: "ハハコグサ",
    scientific_name: "Gnaphalium multiceps",
    description: "春の七草の一つ「御形」として知られるキク科雑草。柔らかい白毛がある。",
    image_url: "",
  },
  {
    name: "カラクサナズナ",
    scientific_name: "Lepidium virginicum",
    description: "ロゼット状に広がる葉と十字形の白花が特徴。外来のアブラナ科雑草。",
    image_url: "",
  },
  {
    name: "タネツケバナ",
    scientific_name: "Cardamine scutata",
    description: "水辺や田んぼ周りに多い。アブラナ科で春に小花をつける。",
    image_url: "",
  },
  {
    name: "イノコヅチ",
    scientific_name: "Achyranthes bidentata",
    description: "果実が衣服にくっつく多年草。茎が太く高さ1m近くにもなる。",
    image_url: "",
  },
  {
    name: "ヤエムグラ",
    scientific_name: "Galium aparine",
    description: "細いトゲで衣類などにくっつく春の雑草。つる性で絡まりやすい。",
    image_url: "",
  },
  {
    name: "コニシキソウ",
    scientific_name: "Euphorbia maculata",
    description: "赤紫の茎が地面を這い、葉に斑点がある。夏に繁殖する一年草。",
    image_url: "",
  },
  {
    name: "メヒシバ",
    scientific_name: "Digitaria ciliaris",
    description: "地面を這うように茎を伸ばすイネ科草本。踏みつけに強い。",
    image_url: "",
  },
  {
    name: "カゼクサ",
    scientific_name: "Eragrostis curvula",
    description: "細い葉と繊細な穂を持つイネ科多年草。風によく揺れる。",
    image_url: "",
  },
  {
    name: "コウガイゼキショウ",
    scientific_name: "Juncus effusus",
    description: "湿地に自生する多年草。円柱形の葉が特徴で、刈り草や工芸材料にも。",
    image_url: "",
  },
  {
    name: "ヌカキビ",
    scientific_name: "Panicum bisulcatum",
    description: "稲に似た穂をつけるイネ科雑草。水田周辺に多く見られる。",
    image_url: "",
  },
  {
    name: "オオアレチノギク",
    scientific_name: "Erigeron canadensis",
    description: "北米原産の外来雑草。背丈が高く、綿毛の種子を多く飛ばす。",
    image_url: "",
  },
  {
    name: "アキノタムラソウ",
    scientific_name: "Salvia japonica",
    description: "紫色の花が秋に咲くシソ科植物。山野に自生する多年草。",
    image_url: "",
  },
  {
    name: "ヤマトリカブト",
    scientific_name: "Aconitum japonicum",
    description: "紫色の兜状の花が特徴だが、有毒植物としても知られる。",
    image_url: "",
  },
  {
    name: "ヒナタイノコズチ",
    scientific_name: "Achyranthes japonica",
    description: "イノコヅチに似ているが、より明るい場所に生える多年草。",
    image_url: "",
  },
  {
    name: "クサギ",
    scientific_name: "Clerodendrum trichotomum",
    description: "葉に臭気があり、赤紫の花と青い実が特徴の低木性雑草。",
    image_url: "",
  },
  {
    name: "ヨウシュヤマゴボウ",
    scientific_name: "Phytolacca americana",
    description: "紫黒色の実が目立つ外来植物。根も茎も有毒で注意が必要。",
    image_url: "",
  },
  {
    name: "ナガエツルノゲイトウ",
    scientific_name: "Alternanthera philoxeroides",
    description: "水辺に群生する外来雑草。環境省の要注意外来生物。",
    image_url: "",
  },
  {
    name: "ヒガンバナ",
    scientific_name: "Lycoris radiata",
    description: "彼岸の頃に赤い花を咲かせる多年草。有毒でモグラ除けにも利用される。",
    image_url: "",
  },
  {
    name: "アレチウリ",
    scientific_name: "Sicyos angulatus",
    description: "つる性の外来雑草。実にトゲがあり、他の植物に絡みつく。",
    image_url: "",
  },
  {
    name: "センダングサ",
    scientific_name: "Bidens pilosa",
    description: "「ひっつき虫」として知られるタネを持つ。キク科の外来植物。",
    image_url: "",
  },
  {
    name: "ヘクソカズラ",
    scientific_name: "Paederia foetida",
    description: "悪臭を放つつる性多年草。白や赤紫の花を咲かせる。",
    image_url: "",
  },
  {
    name: "チガヤ",
    scientific_name: "Imperata cylindrica",
    description: "白い穂が風に揺れるイネ科雑草。根茎で広がる多年草。",
    image_url: "",
  },
  {
    name: "ススキ",
    scientific_name: "Miscanthus sinensis",
    description: "秋の七草の一つ。大きな穂が特徴で、観賞用にもされる多年草。",
    image_url: "",
  },
  {
    name: "セリ",
    scientific_name: "Oenanthe javanica",
    description: "春の七草の一つ。水辺に自生する香りのよい多年草で可食。",
    image_url: "",
  },
  {
    name: "ミズヒキ",
    scientific_name: "Persicaria filiformis",
    description: "赤と白が交互に見える細長い花が特徴。林縁などに生える多年草。",
    image_url: "",
  },
  {
    name: "ヤブガラシ",
    scientific_name: "Cayratia japonica",
    description: "つるで他の植物に覆いかぶさる強勢な雑草。夏にオレンジの花を咲かせる。",
    image_url: "",
  },
  {
    name: "ミチヤナギ",
    scientific_name: "Polygonum arenastrum",
    description: "道端など踏みつけられる環境に適応した這性のタデ科雑草。",
    image_url: "",
  },
  {
    name: "シロバナタンポポ",
    scientific_name: "Taraxacum albidum",
    description: "西日本に多く分布する白い花のタンポポ。在来種。",
    image_url: "",
  },
  {
    name: "ニワゼキショウ",
    scientific_name: "Sisyrinchium rosulatum",
    description: "青紫の小花を咲かせる外来のアヤメ科植物。芝生にも生える。",
    image_url: "",
  },
  {
    name: "ヒメジョオン",
    scientific_name: "Erigeron annuus",
    description: "夏に白い花を多数咲かせる。北アメリカ原産の帰化植物。",
    image_url: "",
  },
  {
    name: "カモガヤ",
    scientific_name: "Dactylis glomerata",
    description: "牧草としても使われるが、花粉症の原因としても有名なイネ科植物。",
    image_url: "",
  },
  {
    name: "アカザ",
    scientific_name: "Chenopodium album",
    description: "白っぽい粉をまとったような葉が特徴。若芽は食用になることも。",
    image_url: "",
  },
  {
    name: "ナズナ",
    scientific_name: "Capsella bursa-pastoris",
    description: "「ペンペングサ」としても知られ、春の七草の一つ。三角の実が特徴。",
    image_url: "",
  },
  {
    name: "ホトケノザ",
    scientific_name: "Lamium amplexicaule",
    description: "春の七草ではなく、よく誤認される。紫色の花が特徴のシソ科植物。",
    image_url: "",
  },
  {
    name: "タビラコ",
    scientific_name: "Lapsana apogonoides",
    description: "春の七草「ほとけのざ」の正体。黄色の花をつけるキク科植物。",
    image_url: "",
  },
  {
    name: "ミゾソバ",
    scientific_name: "Persicaria thunbergii",
    description: "湿地や水辺に多く、ピンクの花を咲かせる。葉に斑点がある。",
    image_url: "",
  },
  {
    name: "イヌビユ",
    scientific_name: "Amaranthus lividus",
    description: "赤紫色を帯びた葉をもつヒユ科の一年草。夏場に多く生える。",
    image_url: "",
  },
  {
    name: "ツルマメ",
    scientific_name: "Glycine soja",
    description: "大豆の原種とされるつる性植物。夏から秋に紫の花を咲かせる。",
    image_url: "",
  },
  {
    name: "ノアザミ",
    scientific_name: "Cirsium japonicum",
    description: "春から初夏に赤紫色の花をつける。トゲが多く虫媒花。",
    image_url: "",
  },
  {
    name: "ノゲシ",
    scientific_name: "Sonchus oleraceus",
    description: "黄色い花をつけるキク科雑草。柔らかい葉は食用にも。",
    image_url: "",
  },
  {
    name: "ウシハコベ",
    scientific_name: "Stellaria aquatica",
    description: "水辺や湿った場所を好むハコベの一種。小さな白い花が特徴。",
    image_url: "",
  },
  {
    name: "セイバンモロコシ",
    scientific_name: "Sorghum halepense",
    description: "大型のイネ科雑草で、穂が赤褐色になる。帰化植物。",
    image_url: "",
  },
  {
    name: "カタバミモドキ",
    scientific_name: "Oxalis debilis",
    description: "ピンクの花を咲かせる外来のカタバミ。庭に生えやすい。",
    image_url: "",
  },
  {
    name: "オオバコ",
    scientific_name: "Plantago asiatica",
    description: "踏みつけに強く道端でよく見かける多年草。種は水にぬれると粘る。",
    image_url: "",
  },
]

weeds.each do |weed|
  Weed.create!(weed)
end
