name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  Web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    timeout-minutes: 10
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v3
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: "${{ github.workspace }}/node_modules"
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Type Check
        run: npm run types-check

      - name: Format Check
        run: npm run format:check

      - name: Lint
        run: npm run lint
